version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: evhcbackend
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ./si-free-space
            dockerfile: Dockerfile
        container_name: evhc-frontend
        ports:
            - "5173:5173"
